[package]
name = "apple-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
block = "0.1.6"
objc = { version = "0.2.7", features = ["exception", "objc_exception", "verify_message"] }

[build-dependencies]
glob = "0.3.1"
bindgen = "0.69.4"

