[package]
name = "elp_parser"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
pretty_assertions = "1.4.0"

[dependencies]
async-trait = "0.1.81"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = { version = "1.0.120", features = ["unbounded_depth"] }
