[package]
name = "apple-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2.7"
block = "0.1.6"

[build-dependencies]
bindgen = "0.65.1"

[workspace]
